name: Pack

on:
    push:
        tags:
            - '*'

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.0.x
            - name: Restore dependencies
              run: dotnet restore Starfish.Build.slnf
            - name: Build
              run: dotnet build Starfish.Build.slnf --no-restore --configuration Release
            - name: Pack
              run: dotnet pack Starfish.Build.slnf -c Release -o artifacts/
            - name: Publish NuGet
              run: dotnet nuget push artifacts/*.nupkg --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate